[world]
# Number of chunks in each direction from the player
world_dimension = 16
# Number of chunks to preload (adds on top of world_dimension)
preload_extra_distance = 2

[logs]
triangle_count_enabled = true
change_chunk_enabled = true
update_as_we_move_enabled = true